name: rwkv-lora-pat
channels:
  - defaults
dependencies:
  - python=3.10.14
  - datasets=2.12.0
  - huggingface_hub=0.20.3
  - transformers=4.37.2
  - pip=24.0
  - pip:
      - accelerate==0.30.1
      - bitsandbytes==0.43.1
      - einops==0.8.0
      - peft==0.11.2.dev0
      - torch==2.3.0
      - trl==0.8.6
