###############################################
#  Now used for
#+     'full_environment.yml'
#+   which has everything, including 
#+   platform-specific stuff (Windows, here)
#+ AND
#+     'environment.yml'
#+   a meant-to-be OS-agnostic package list
#======

# @file: environment-cpu.yml
# @since 2024-07-25
## 1721754699_2024-07-23T17:11:39-0600
## IMPORTANT NOTES
##
##  A couple of installations were made from git repos. (These next commands
##+ were the originals - look below for the commands needed for 
##+ reproducibility.)
##     >pip install git+https://github.com/huggingface/peft.git
##     >pip install git+https://github.com/nexplorer-3e/qwqfetch
##
##  The commit info will be important for reproducibility.
##
##-----
##  qwqfetch   for system info
##
##   Resolved https://github.com/nexplorer-3e/qwqfetch \
##       to commit f72d222e2fff5ffea9f4e4b3a203e4c4d9e8cf00
##   Successfully installed qwqfetch-0.0.0
##
##  !!!!! So, the command should be !!!!!
##
## (Windows CMD)
##>pip install git+https://github.com/huggingface/qwqfetch.git@^
## e7b75070c72a88f0f7926cc6872858a2c5f0090d
##
## (Windows PowerShell)
##>pip install git+https://github.com/huggingface/qwqfetch.git@`
## e7b75070c72a88f0f7926cc6872858a2c5f0090d
##
## (*NIX-like)
##$ pip install git+https://github.com/huggingface/qwqfetch.git@\
##  e7b75070c72a88f0f7926cc6872858a2c5f0090d
##  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
##-----
##  peft: I installed PEFT among other things, but I'm picking out 
##+       stuff relevant to peft. PEFT has LoRA in it.
##
##   Resolved https://github.com/huggingface/peft.git \
##       to commit e7b75070c72a88f0f7926cc6872858a2c5f0090d
##   Successfully built peft
##
##  !!!!! So, the command should be !!!!!
## (Windows CMD)
##>pip install git+https://github.com/huggingface/peft.git@^
## e7b75070c72a88f0f7926cc6872858a2c5f0090d
##
## (Windows PowerShell)
##>pip install git+https://github.com/huggingface/peft.git@`
## e7b75070c72a88f0f7926cc6872858a2c5f0090d
##
## (*NIX-like)
##$ pip install git+https://github.com/huggingface/peft.git@\
##  e7b75070c72a88f0f7926cc6872858a2c5f0090d
##  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
###############################################

name: t5-and-lora
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.1.2
  - pip:
      - pip==24.1.2
      - accelerate==0.30.1
      - bitsandbytes==0.43.1
      - datasets==2.19.1
      - evaluate==0.4.2
      - huggingface-hub==0.23.2
      - humanfriendly==10.0
      - jupyter==1.0.0
      - nltk==3.8.1
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pylspci==0.4.3
      - rouge-score==0.1.2
      - torch==2.3.0
      - transformers==4.41.1
      - trl==0.8.6
      - wmi==1.5.1
